### ISSUE TITLE
Realm issue?

### ISSUE THREAD

**Issue by Hades546** [js802025/calcmod#20]
Could be related to trying to run it on a realm rather than a normal server. Cause the command doesn't want to show up in chat on the realm for some reason.

**Comment by js802025** [comment]
your running calcmod on your client?

**Comment by Hades546** [comment]
yes

**Comment by js802025** [comment]
Unfortunately, I do not have a realm so I can't really test but do other mods work on your realm? And do you have like a log you could upload from your client?

**Comment by js802025** [comment]
It has been tested on realms now and confirmed working. I'm closing this issue for now, but if you have further troubles comment again.
