### ISSUE TITLE
Hopper clock timing are wrong

### ISSUE THREAD

**Issue by NotSoNitro** [js802025/calcmod#23]
i've tested out the hopper clock timing and they seem to be wrong, i think whatever calculation u have isn't correct. Please do check it out because this would be really useful to have

**Comment by shadeydo** [comment]
the responses in CalcMod seem to be consistent with [https://hoppertimer.net](https://hoppertimer.net), is there a chance you are using a different hopper timer than the one pictured on the site?

**Comment by NotSoNitro** [comment]
Whenever I used it the timings were off, I haven't tried to hopper clocks on https://hoppertimer.net so I'll try that as well, if it helps I'm trying to use it on a PaperMC server. Gave me the same result as single player where the timings seemed off.

**Comment by js802025** [comment]
would you mind sending a screenshot of the clock your using, as well as the mc version?

**Comment by NotSoNitro** [comment]
Here's a clip of me showing the hopper clock and the fact that its not right: https://notsonitro.needs.rest/2024-01-10_16-47-38.mp4

I believe it might be a PaperMC issue but it does the same on a single player world so right now im somewhat confused. Also the MC Version im playing on is 1.20.4

**Comment by shadeydo** [comment]
if you take the output from either comparator instead of the redstone block, I believe the timing should be correct. I will change the wording in the wiki to make this more clear in the future!
