### ISSUE TITLE
Recursive recipe calculation

### ISSUE THREAD

**Issue by ThisIsKevin01** [js802025/calcmod#26]
Is it possible to make command /calc craft <item> <amount> recursively calculate the recipe of an item to raw materials? Say calculate a hopper will output the recipe of chest and iron. I want the chest also be calculated all the way to log. Another thought is that I feel I will use /calc craft command a lot, so maybe add a alias for that command like /cc <item> <amount>?

**Comment by js802025** [comment]
Thanks for the suggestion!. It has been added in our latest 1.3.2 beta, which is available on modrinth: https://modrinth.com/mod/calcmod/version/cYbHF2E2.
