### ISSUE TITLE
Semantic Versioning?

### ISSUE THREAD

**Issue by UltimatChamp** [js802025/calcmod#27]
https://semver.org/

For example, the latest version can be written as:
~fabric-1.20.2-1.3.1~ → `1.3.1+fabric.1.20.2`

For pre-releases:
`1.4.0-beta+fabric.1.20.5`
`1.4.0-alpha+fabric.1.20.5`

This will also prevent a warning in the log for Fabric versions, 'to use SemVer'.

**Comment by js802025** [comment]
Thanks for the suggestion the latest version uses it.
