### ISSUE TITLE
calcmod-forge-1.19.4-1.3.0.jar needs language provider javafml:45 or above to load

### ISSUE THREAD

**Issue by FatalDarknessReal** [js802025/calcmod#29]
I am using 1.19.2 Minecraft forge and just downloaded CalcMod for this version (1.19-1.19.4) and its just making Minecraft crash with error "calcmod-forge-1.19.4-1.3.0.jar needs language provider javafml:45 or above to load"

**Comment by shadeydo** [comment]
aha yes thanks for bringing this to our attention. CalcMod is only officially tested on the newest and oldest versions of major releases (1.19.0 and 1.19.4), and it seems 1.19.2 slipped through the cracks. anyway i updated things so it no longer says 1.19.2 is supported
