### ISSUE TITLE
It isn't actually compatible with 1.20.6

### ISSUE THREAD

**Issue by Antstone2898** [js802025/calcmod#30]
It crashes
[crash-calc-client.txt](https://github.com/js802025/calcmod/files/15182994/crash-calc-client.txt)
It also doesn't crash without calc.

**Comment by js802025** [comment]
when does it crash?

**Comment by Antstone2898** [comment]
When opening minecraft.

**Comment by Antstone2898** [comment]
It is in calcmod/src/main/java/net/jsa2025/calcmod/commands/subcommands/Nether.java
I think it is _import dev.xpple.clientarguments.arguments.CBlockPosArgumentType;_

**Comment by js802025** [comment]
From my tests I have determined it to be an incompatibility with client commands in 1.20.6. I will try to publish a patch over the weekend

**Comment by js802025** [comment]
This has been fixed in the latest beta, which should be available on modrinth here: https://modrinth.com/mod/calcmod/version/cYbHF2E2.
