### ISSUE TITLE
1.3.2-beta+fabric.1.20.6 is listed as compatible with 1.20.2-1.20.6 but requires Java 21

### ISSUE THREAD

**Issue by NotRyken** [js802025/calcmod#33]
The [Modrinth listing](https://modrinth.com/mod/calcmod/version/1.3.2-beta+fabric.1.20.6) for `1.3.2-beta+fabric.1.20.6` specifies the compatibility range as 1.20.2-1.20.6. However, because it was compiled against Java 21 it cannot be run on 1.20.2-1.20.4 instances which use Java 17.

This *can* be fixed on the user-side by modifying the instance to use Java 21, but in my opinion that should not be required.

**Comment by js802025** [comment]
Yeah that was a mistake. The 1.3.2 version is currently only available for 1.20.6. Thanks for pointing this out, it has been corrected.
