### ISSUE TITLE
Fabric API dependency uses old mod ID `fabric` instead of `fabric-api`

### ISSUE THREAD

**Issue by NotRyken** [js802025/calcmod#34]
In [`fabric.mod.json`](https://github.com/js802025/calcmod/blob/a1297b05b1e77b9741765696876bae78d95020be/src/main/resources/fabric.mod.json#L30), the dependency on Fabric API uses the old mod ID `fabric`. [The mod ID was changed to `fabric-api` in 1.19.2](https://fabricmc.net/wiki/tutorial:setup) to improve clarity.

`fabric` remains valid but is less helpful for users, who may reasonably think that it refers to Fabric Loader instead of the Fabric API mod.

**Comment by js802025** [comment]
fixed in 1.21 thanks!
